### ISSUE TITLE
new manylinux wheel causes ImportError

### ISSUE THREAD

**Issue by ifundef** [python-greenlet/greenlet#101]
the wheel presumably created by the work done in https://github.com/python-greenlet/greenlet/issues/100 causes import errors on debian wheezy running cpython 2.7.3.

```
# pip install greenlet
Collecting greenlet  
<snip SNIMissingWarning & InsecurePlatformWarning messages>
  Downloading greenlet-0.4.9-cp27-cp27mu-manylinux1_x86_64.whl (41kB)
    100% |################################| 51kB 775kB/s
Installing collected packages: greenlet
Successfully installed greenlet-0.4.9
# python -c 'import greenlet'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /root/venv/local/lib/python2.7/site-packages/greenlet.so: undefined symbol: _PyTrash_thread_deposit_object
# cat /etc/issue.net
Debian GNU/Linux 7
# python --version
Python 2.7.3
# md5sum $(which -a python)
9d6ffa5c2c1d97ce544a2969f66d70fd  /root/venv/bin/python
9d6ffa5c2c1d97ce544a2969f66d70fd  /usr/bin/python
# dpkg -S /usr/bin/python
python-minimal: /usr/bin/python
# dpkg -l python-minimal
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  python-minimal 2.7.3-4+deb7 all          minimal subset of the Python lang
```

**Comment by snaury** [comment]
Yes, I built and uploaded them in response to #100.

**Comment by snaury** [comment]
That's very unfortunate, but it is the direct result of Python 2.7.4+ breaking binary compatibility in trashcan APIs, and for good reason (http://bugs.python.org/issue13992 if I'm not mistaken, found it via Python changelog). I'm not sure what I can do, since compiling on Python 2.7.3 makes greenlet unsafe, and compiling on 2.7.4+ makes it stop working on 2.7.3.

Perhaps debian could backport trashcan changes to 2.7.3?

**Comment by snaury** [comment]
I think you can work it around by using `pip install --no-binary all greenlet`.

**Comment by ifundef** [comment]
yes, `--no-binary :all:` works, but greenlet is a third-order dependency installed by `pip install --requirements requirements.txt`.

researching how to do that now (or if it is even possible).

**Comment by snaury** [comment]
After some more thinking I pulled manylinux1 wheels for greenlet 0.4.9, since uploading them in the first place was a big mistake. I will bring them back in greenlet 0.4.10.

**Comment by ifundef** [comment]
@snaury thanks for the near-term fix of removing and manylinux wheel and helping me work through the future-term issue of having pip avoid the wheel.

**Comment by andyhky** [comment]
+1, thanks for the quick fix!

**Comment by balloob** [comment]
Is there a timeline when to expect a 0.4.10 build that includes the manylinux wheels?

**Comment by snaury** [comment]
Not really. The only thing stopping me right now is the need to build Windows binaries for so many Python versions, which requires a lot of Pythons and Visual Studios installed, and since I haven't used Windows at all for the last two years my last laptop has none of that at the moment.

I have a very old laptop that had all the necessary setup, but stars need to collide when I'm at my old place and actually want to do any meaningful work. There's a good chance that stars WILL collide next week, so thanks for the reminder! :)

**Comment by balloob** [comment]
Based on the commits on master there seemed to be no changes since the 0.4.9 release. Wouldn't you be able to just upload the same wheels for 0.4.10 but also include a manylinux wheel?

Thanks for your work btw 👍

**Comment by saghul** [comment]
I have successfully used AppVeyor both as a CI and as a wheel building
service, since they keep the built artifacts. Have a look!

**Comment by snaury** [comment]
> I have successfully used AppVeyor both as a CI and as a wheel building service, since they keep the built artifacts. Have a look!

Wow, thank you for the suggestion! Found the [python-appveyor-demo](https://github.com/ogrisel/python-appveyor-demo) project and it seems to be exactly what I needed. Way better than relying on some old laptop!

**Comment by saghul** [comment]
Yeah, I took that project as a base too, since my PowerShell kung-fu is non-existent :-) 10/10 would recomment.

**Comment by frwickst** [comment]
Hi, sorry if I'm hijacking the thread but there seems to be some problems with running 0.4.10 on Python 2.7.3. 

I noticed this the hard way after when running gunicorn with gevent just now. gevent does not seem to pin the version of greenlet they are using, instead they go with `greenlet >= 0.4.9`, well this installed 0.4.10, and when I try to import gevent I get the same import error as @ifundef got: `... undefined symbol: _PyTrash_thread_deposit_object`. I tried installing just greenlet 0.4.10 (in a virtualenv v.15.0.2) and importing greenlet directly gives me the same error. 0.4.9 works just fine.

The reason for running on Python 2.7.3 is Debian Wheezy is stuck on this version.

**Comment by snaury** [comment]
> The reason for running on Python 2.7.3 is Debian Wheezy is stuck on this version.

Python 2.7.3 is 4 years old and Python 2.7.4 knowingly changed to thread-safe trashcan ABI, with a known side effect of extensions compiled on 2.7.4+ not loadable on 2.7.3, see: https://mail.python.org/pipermail/python-checkins/2012-September/115893.html

Since official docker containers for building manylinux1 wheels use the latest version of Python it's a lot less easy to provide manylinux1 wheels built with older versions of Python. Besides, using an old thread-unsafe version of trashcan does not sound compelling.

To be honest greenlet could probably get away with not using trashcan at all. I just did a quick test and custom attributes already (indirectly) use trashcan, since they are stored in an internal dict. But very long chains of `parent` attributes do not, however I couldn't even construct a chain of 1 million of them in a reasonable time, since the process practically crawls to a halt at around ~100k of them (which is not surprising given it's `O(n^2)` complexity). Thus it's probably safe to assume nobody uses such long chains of greenlets in reality, but you never know. :(

**Comment by balloob** [comment]
You can pip install greenlet 0.4.9 before installing gevent and pip should not have to install 0.4.10

**Comment by frwickst** [comment]
@balloob: Yes, this was my solution to the problem as well but I really think that Gevent should start pinning to versions instead of using >=, as this would also catch new major versions.

**Comment by coreywright** [comment]
this is not the first problem i've encountered with manylinux1 packages and has prompted me to create https://github.com/coreywright/nomanylinux.

**Comment by amitsaha** [comment]
@snaury referring to your earlier comment above:

> Since official docker containers for building manylinux1 wheels use the latest version of Python it's a lot less easy to provide manylinux1 wheels built with older versions of Python. Besides, using an old thread-unsafe version of trashcan does not sound compelling.

Not sure I understand this, since I see this:

```
$ docker run -ti quay.io/pypa/manylinux1_x86_64  python
Python 2.4.3 (#1, Jan  9 2013, 06:47:03) 
[GCC 4.1.2 20080704 (Red Hat 4.1.2-54)] on linux2
```

**Comment by snaury** [comment]
Manylinux builds use python versions installed in /opt/python.

**Comment by gukoff** [comment]
`--no-binary` didn't work, but `pip install --no-use-wheel greenlet==0.4.11` helped me.

**Comment by gukoff** [comment]
The only way I made it work with the `requirements.txt` file was using the deprecated `--no-use-wheel` option like this:

```
...
gevent==1.2.0
greenlet==0.4.11  --no-use-wheel
itsdangerous==0.24
...
```

**Comment by snaury** [comment]
A colleague finally explained to me how people get hit by this when using virtualenv, so I made a new 0.4.12 release that doesn't use trashcan anymore. I hope it works for all of you now!
