### ISSUE TITLE
Greenlet 0.4.10 wheel doesn't work on python 2.7.3

### ISSUE THREAD

**Issue by jogo** [python-greenlet/greenlet#111]
https://pypi.python.org/packages/fd/4b/108108a5a4234b2c7f81a7e9513950caf5146c9b2d47664348dbe9aebaf8/greenlet-0.4.10-cp27-cp27mu-manylinux1_x86_64.whl#md5=eb175d2b16766004abc16f5b23a8ad99  Fails on python 2.7.3. It raises 
`ImportError: /usr/local/lib/python2.7/dist-packages/greenlet.so: undefined symbol: _PyTrash_thread_deposit_object` This looks to be a duplicate of issue #39, the wheel was built with Python >=2.7.4. And since pip simply says the wheel is compatible with cp27	, pip installs a broken wheel.

**Comment by snaury** [comment]
This is a known issue and works as expected, please don't use python 2.7.3. Use system packages if you have to use system python and it has version 2.7.3.

**Comment by jogo** [comment]
@snaury thank you for the response. Do you think this means there is an upstream issue with wheels not being able to specify version incompatibility?

**Comment by snaury** [comment]
I'm not sure if that's an issue with wheels, as far as I remember (from some python-dev thread) this was a deliberate decision to break binary compatibility, since the API is supposedly undocumented and nobody should have used it, and previous version was unsafe and crashing. Really it's been 4.5 years and many important fixes happened since 2.7.3, I'd advise to upgrade. Again, if you are using a system version of Python, why do you try to install from pip? There's a `python-greenlet` package in debian repositories.

**Comment by Shr3ps** [comment]
It seems that Greenlet 0.4.12 and Greenlet 0.4.13 are working fine with Python 2.7.3 (on Debian Wheezy for example).
