### ISSUE TITLE
How does g_switch throw an exception in the target greenlet if an exception is set?

### ISSUE THREAD

**Issue by tbodt** [python-greenlet/greenlet#114]
It seems, based on the implementation of green_throw and a few other things, that if an exception is set, g_switch will throw it in the target greenlet. But looking at g_switchstack, I don't understand how that can work. It seems to save the current set exception in the current greenlet, then restore the exception from the target greenlet, thus overwriting the currently set exception with (often) nothing. How does it work?

**Comment by tbodt** [comment]
Guess I didn't understand how python exceptions are implemented. Setting an exception sets curexc_{type,val,tb} and g_switchstack doesn't touch those.

**Comment by tbodt** [comment]
BTW I'm down to 2 test failures on my libcoro version of greenlet.

**Comment by snaury** [comment]
Switching and throwing are not much different. In Python C-API functions usually returns non-NULL if it has a result, and returns NULL if it throws an exceptions, in the latter case it should be set first. When you switch or throw to another greenlet, that function only returns if it was a switch or throw back. So if green_switch or green_throw returns NULL it was a throw, otherwise they return a tuple and don't throw. Now g_switch itself doesn't actually deal with exceptions, it only cares about what to return on the other side. What green_throw is doing is a pretty standard exception normalization, then in throw_greenlet it simply restores that and calls g_switch(self /* target */, NULL, NULL), throwing the restored exception in the target greenlet, except in a rare special case of handling GreenletExit.
