### ISSUE TITLE
Freeze in attempt to switch() from signal handler

### ISSUE THREAD

**Issue by arachnopavel** [python-greenlet/greenlet#143]
Hello.

I'm trying to implement a kind of preemptive scheduling for greenlets, utilizing the fact that Python's signal handler functions are actually executed in the context of main control flow.

The code below works fine with greenlet 0.4.13 module built into PyPy3.5 v7.0.0, but freezes with greenlet 0.4.x in CPython 3.5.3 and 2.7.13.

```python
import greenlet
import signal
import sys

from collections import OrderedDict


_counters = {}
_main_greenlet = greenlet.getcurrent()


def timer_handler(signum, frame):
    try:
        print("timer, {}".format(_counters))
        if greenlet.getcurrent() is not _main_greenlet:
            print("switching to main")
            _main_greenlet.switch()
        else:
            print("already in main, not switching")
    except RuntimeError as rte:
        if "reentrant call" not in rte.args:
            raise

def set_timer(t, handler=timer_handler):
    signal.signal(signal.SIGALRM, handler)
    signal.setitimer(signal.ITIMER_REAL, t, t)

def f(counter_id):
    if counter_id not in _counters:
        _counters[counter_id] = 0
    while True:
        _counters[counter_id] += 1

if __name__ == "__main__":
    try:
        try:
            n = int(sys.argv[1])
        except:
            n = 10
        children = OrderedDict()
        for i in range(n):
            def fi(x=i):
                f(x)

            g = greenlet.greenlet(fi)
            children["g{}".format(i)] = g

        try:
            t = float(sys.argv[2])
        except:
            t = 0.1
        set_timer(t)

        while True:
            for g in children:
                print("switching to {}".format(g))
                children[g].switch()
    except KeyboardInterrupt:
        try:
            print("interrupted, {}".format(_counters))
        except:
            pass
```
Any clues?

**EDIT**: almost forgot... This simpler code works on both CPython 3.5.3 and 2.7.13:
```python
import greenlet
import signal

iter_count = 0

def f1():
    global iter_count
    while True:
        iter_count += 1
        pass

g1 = greenlet.greenlet(f1)

def f2():
    while True:
        print("switch, {}".format(iter_count))
        g1.switch()

g2 = greenlet.greenlet(f2)

def handler(signum, frame):
    print("timer, {}".format(iter_count))
    g2.switch()

signal.signal(signal.SIGALRM, handler)
signal.setitimer(signal.ITIMER_REAL, 0.1, 0.1)

try:
    g2.switch()
except:
    print("interrupted, {}".format(iter_count))
```

**Comment by snaury** [comment]
I think the problem in your case is that you never actually return from the signal handler. CPython handles signals using pending calls mechanism, which are not reentrant and will be postponed until the last pending call has completed (otherwise signal handlers would have been recursive, which would have been messy).

Your timer_handler runs in g0 and switches to main, which then switches to g1. In g1 the actual signal hits again and again, but all it does is setting the relevant "tripped" flag, and Py_MakePendingCalls repeatedly observes the busy flag, so your handler is never called.

Sorry, but it looks like doing preemption this way won't work in CPython, unless you somehow start tracing inside your signal handler and wait until you're no longer in any pending call, which is way too tricky.

**Comment by jamadden** [comment]
This may be worth adding to a new "Known Issues" or "Things Not To Do" section in the docs.
