### ISSUE TITLE
SuperH/sh4 architecture unsupported

### ISSUE THREAD

**Issue by jameshilliard** [python-greenlet/greenlet#166]
I'm seeing this error when building greenlet using buildroot's ci [here](http://autobuild.buildroot.net/results/cd7/cd748aa26fdabcef72a581e1fe26edac14d07d2d/build-end.log).
```
greenlet needs to be ported to this platform, or teached how to detect your compiler properly.
```
If supporting this architecture is not possible I can flag greenlet as incompatible but it would be ideal to add support.

**Comment by jamadden** [comment]
PRs are welcome!

**Comment by noloader** [comment]
Debian is having an issue, too. See [Debian Bug 1025176](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1025176).

Unfortunately, the missing support is blocking users from installing GDB on SH4.

**Comment by jamadden** [comment]
Essentially all that should need done is implementing `slp_switch()` in a new platform-specific header in `src/greenlet/platform/`, and adding the selection criteria to `src/greenlet/slp_platformselect.h`. The platform-specific header will also have to define `STACK_MAGIC`; for how it is used see `src/greenlet/greenlet_slp_switch.hpp`.

**Comment by jamadden** [comment]
> On Nov 16, 2023, at 05:58, John Paul Adrian Glaubitz ***@***.***> wrote:
> 
> 
> If I understand correctly, the task of slp_switch() is to save and restore a thread environment?

Yes, it does the actual work of dealing with the processor state, including stack pointer.

The greenlet code shares a common heritage with Stackless CPython (https://github.com/stackless-dev/stackless/); sometime after greenlet was created, the Stackless devs factored that code out into a separate library called stackman (https://github.com/stackless-dev/stackman). There may be additional examples and/or documentation in those repos that are helpful. 

(Ultimately, it would be nice to have greenlet use stackman so that there's only one place (or at least, one fewer place) where code like this needs to be maintained.)

**Comment by pietro** [comment]
@glaubitz can you test the code at #398 ?

**Comment by glaubitz** [comment]
> @glaubitz can you test the code at #398 ?

I'll test it today and let you know.

There is currently a large transition going on in Debian which why you probably couldn't install Python in QEMU.

**Comment by glaubitz** [comment]
It builds fine in qemu-user, but for running the testsuite, I need to run it on real hardware.

My SH7785LCR development board is currently busy rebuilding the Perl interpreter for Debian's time64_t transition, but I will test it right after that as soon as possible.

**Comment by glaubitz** [comment]
> PRs are welcome!

Any chance this can be merged? https://github.com/python-greenlet/greenlet/pull/401
