### ISSUE TITLE
1.0.0: strange installed files

### ISSUE THREAD

**Issue by kloczek** [python-greenlet/greenlet#231]
Content of the python sitepackage directore after install in DESTDIR
I suppose that header files and `greenlet/tests` shpuld not be actually installed 
Or in case header fierls they should not be installed in that location.
Could you please confirm or make some comment?

I've bolded files which I think that shpuld not be installed.

>[tkloczko@barrel site-packages]$ find . -name \*
.
./greenlet
./greenlet/__init__.py
**/greenlet/tests
./greenlet/tests/__init__.py
./greenlet/tests/test_contextvars.py
./greenlet/tests/test_cpp.py
./greenlet/tests/test_extension_interface.py
./greenlet/tests/test_gc.py
./greenlet/tests/test_generator.py
./greenlet/tests/test_generator_nested.py
./greenlet/tests/test_greenlet.py
./greenlet/tests/test_leaks.py
./greenlet/tests/test_stack_saved.py
./greenlet/tests/test_throw.py
./greenlet/tests/test_tracing.py
./greenlet/tests/test_version.py
./greenlet/tests/test_weakref.py
./greenlet/tests/_test_extension.c
./greenlet/tests/_test_extension_cpp.cpp
./greenlet/tests/_test_extension_cpp.cpython-38-x86_64-linux-gnu.so
./greenlet/tests/_test_extension.cpython-38-x86_64-linux-gnu.so
./greenlet/greenlet.c
./greenlet/greenlet.h
./greenlet/slp_platformselect.h
./greenlet/platform
./greenlet/platform/setup_switch_x64_masm.cmd
./greenlet/platform/switch_aarch64_gcc.h
./greenlet/platform/switch_alpha_unix.h
./greenlet/platform/switch_amd64_unix.h
./greenlet/platform/switch_arm32_gcc.h
./greenlet/platform/switch_arm32_ios.h
./greenlet/platform/switch_csky_gcc.h
./greenlet/platform/switch_m68k_gcc.h
./greenlet/platform/switch_mips_unix.h
./greenlet/platform/switch_ppc64_aix.h
./greenlet/platform/switch_ppc64_linux.h
./greenlet/platform/switch_ppc_aix.h
./greenlet/platform/switch_ppc_linux.h
./greenlet/platform/switch_ppc_macosx.h
./greenlet/platform/switch_ppc_unix.h
./greenlet/platform/switch_riscv_unix.h
./greenlet/platform/switch_s390_unix.h
./greenlet/platform/switch_sparc_sun_gcc.h
./greenlet/platform/switch_x32_unix.h
./greenlet/platform/switch_x64_masm.asm
./greenlet/platform/switch_x64_masm.obj
./greenlet/platform/switch_x64_msvc.h
./greenlet/platform/switch_x86_msvc.h
./greenlet/platform/switch_x86_unix.h**
./greenlet/_greenlet.cpython-38-x86_64-linux-gnu.so
./greenlet-1.0.0-py3.8.egg-info
./greenlet-1.0.0-py3.8.egg-info/PKG-INFO
./greenlet-1.0.0-py3.8.egg-info/not-zip-safe
./greenlet-1.0.0-py3.8.egg-info/dependency_links.txt
./greenlet-1.0.0-py3.8.egg-info/requires.txt
./greenlet-1.0.0-py3.8.egg-info/top_level.txt
./greenlet-1.0.0-py3.8.egg-info/SOURCES.txt

**Comment by jamadden** [comment]
Tests and headers are installed in those locations on purpose.

**Comment by kloczek** [comment]
Thx

**Comment by jamadden** [comment]
- When troubleshooting and assisting users with bug reports, it's important (for the users) to be able to run the tests in an installed system. This is especially true for less-used platforms or new versions of platforms. Just because 'pip install greenlet' worked doesn't necessarily mean that everything is copacetic. 
- In certain build environments, it's easier to find the headers as data files beside the installed Python files than it is in the standard include directory. Indeed, some environments don't actually manage a standard include directory so headers can't be found there at all. (I've experienced this with buildout in the past.)
- The header and source files can also be useful in troubleshooting for more experienced users, or just to help get an understanding of how things work for the curious.
