### ISSUE TITLE
undefined symbol: _PyTrash_thread_deposit_object

### ISSUE THREAD

**Issue by skbohra** [python-greenlet/greenlet#24]
I am using gevent socketio package, which requires greenlet, but I am getting this error when using the package

../lib/python2.7/site-packages/greenlet-0.4.0-py2.7-linux-i686.egg/greenlet.so: undefined symbol: _PyTrash_thread_deposit_object

**Comment by pjwerneck** [comment]
In case anyone is still having this issue, _PyTrash_thread_deposit_object was introduced in Python 2.7.4, so you're probably trying to run greenlet compiled for Python 2.7.4+ with an older Python 2.7 version. We had this problem here with someone uploading a greenlet wheel compiled for Python 2.7.10 to our localshop.

**Comment by abs07** [comment]
@pjwerneck Mate : Could you please help me in solving the issue. I am totally noob.
