### ISSUE TITLE
Can greenlet object be cloned with its running states? 

### ISSUE THREAD

**Issue by wang0618** [python-greenlet/greenlet#287]
When a greenlet object `g1` is not running, I want make a clone `g2` of it and then switch to `g1` but keep `g2` not be affected, meanwhile `g1` and `g2` share the same closure variables. 

[Cloning python native generators](http://stupidpythonideas.blogspot.com/2015/04/cloning-generators.html) seems be challenging. So I wonder can this be aricheved in greenlet. Any information would be greatly appreciated.

**Comment by jamadden** [comment]
That's not possible now. I was thinking that in theory a shallow copy might be possible, but the problem is: what happens when the greenlet finishes? Execution resumes in the parent when a greenlet finishes, and you can't have two resumes in the parent at the same place. So no, I don't think this is possible.
