### ISSUE TITLE
When running `poetry install`, I get "Unable to find installation candidates for greenlet (1.1.3.post0)"

### ISSUE THREAD

**Issue by goulter** [python-greenlet/greenlet#316]
• Updating greenlet (1.1.2 -> 1.1.3.post0): Failed
```
  RuntimeError

  Unable to find installation candidates for greenlet (1.1.3.post0)

  at ~/Library/Application Support/pypoetry/venv/lib/python3.8/site-packages/poetry/installation/chooser.py:103 in choose_for
       99│ 
      100│             links.append(link)
      101│ 
      102│         if not links:
    → 103│             raise RuntimeError(f"Unable to find installation candidates for {package}")
      104│ 
      105│         # Get the best link
      106│         chosen = max(links, key=lambda link: self._sort_key(package, link))```

Running Mac OS Majove 10.14.6
Poetry 1.2.1
Python 3.8.6
Pip 22.2.2

**Comment by jamadden** [comment]
You can see that [1.1.2](https://pypi.org/project/greenlet/1.1.2/#files) published [greenlet-1.1.2-cp38-cp38-macosx_10_14_x86_64.whl](https://files.pythonhosted.org/packages/e7/b3/e4f84cd23ea46676dd88c514457ca0bad7a8efe40be76cffc009fed4b16e/greenlet-1.1.2-cp38-cp38-macosx_10_14_x86_64.whl), and [1.1.3.post0](https://pypi.org/project/greenlet/1.1.3.post0/#files) published [greenlet-1.1.3.post0-cp38-cp38-macosx_10_15_x86_64.whl](https://files.pythonhosted.org/packages/60/46/1d91ad002b3978991ecd1c1f24af47de44123987521ec1266e86b4e54b95/greenlet-1.1.3.post0-cp38-cp38-macosx_10_15_x86_64.whl). 

The filename tags changed because GitHub Actions changed the version of macOS that's available to the builders in the [13 months since 1.1.2](https://github.com/python-greenlet/greenlet/actions/runs/1286427912) was built. Even if I had the time or inclination to try to configure GHA to also run non-default, old versions of the builders (I do not), [10.15 is the oldest version GHA makes available](https://github.com/actions/runner-images/tree/macOS-11/20221002.2/images/macos), so it doesn't look like that's a solution.

That said, binary wheels are a convenience, not a guarantee. The same source distribution is provided, so just let your tool build from source.

**Comment by tomthorogood** [comment]
@goulter are you able to pin 1.1.2?

**Comment by goulter** [comment]
@tomthorogood I just wound up doing `pip install greenlet`. I think I need to run my OS update, as newer OS versions don't seem to have this issue.

**Comment by tomthorogood** [comment]
good to know, just glad you're unblocked!
