### ISSUE TITLE
Dependency on a yanked version of protobuf

### ISSUE THREAD

**Issue by ranjanicanva** [python-greenlet/greenlet#345]
Hi, 

When I am pulling/building via bazel the latest released version of greenlet (2.0.2), I am getting the following error:
```
Failed to build greenlet
 (WARNING: The candidate selected for download or install is a yanked version: 'protobuf' candidate (version 4.21.0 at https://files.pythonhosted.org/packages/4a/a1/bca58f61cf6a36606cb8b12dd9f2dfa0cadde02dcd9e76a81fe3da77ba42/protobuf-4.21.0-cp37-abi3-macosx_10_9_universal2.whl#sha256=157e4ad67bf75d5719516fbf13fd652c634fd71338e01d2ac872bf365213b7a6 (from https://pypi.org/simple/protobuf/))
Reason for being yanked: Required python version not configured correctly (https://github.com/protocolbuffers/protobuf/issues/10076)
  error: subprocess-exited-with-error

```

and further down:
```
      src/greenlet/greenlet.cpp:9:10: fatal error: 'cstdlib' file not found
      #include <cstdlib>
               ^~~~~~~~~
      1 error generated.
      error: command '/nix/store/775qg9dwdhp524smfjn3868jbwfdf00n-clang-wrapper-11.1.0/bin/clang' failed with exit code 1
      [end of output]
```

I am not sure what I might be missing?

**Comment by jamadden** [comment]
This project has nothing to do with `protobuf`, so that dependency must be coming from somewhere else (this project, in fact, has zero dependencies).

> `       src/greenlet/greenlet.cpp:9:10: fatal error: 'cstdlib' file not found`

`cstdlib` is a [standard C++ header](https://en.cppreference.com/w/cpp/header/cstdlib), so this suggests there is something wrong with your compiler environment or the compilation settings.

It looks like you're using clang on Linux, which is a combination not tested by this project's CI, so I haven't seen this before and I don't know how to help you. There may be more information in the verbose output. I am somewhat surprised, though, that no pre-built binary wheel was used. We supply a lot of them...

**Comment by ranjanicanva** [comment]
Thanks @jamadden for the quick response! Let me investigate it further on my end 👍
