### ISSUE TITLE
Python 2.7 test failures on several architectures

### ISSUE THREAD

**Issue by gcsideal** [python-greenlet/greenlet#63]
I try to compile 0.4.4 for various architectures. It compiles, but its Python 2.7 self-tests are failing with various code related errors like 'segmentation fault' and 'Illegal instruction'. You may see the last few lines of the tests at https://buildd.debian.org/status/package.php?p=python-greenlet&suite=unstable Can it be related to the ASM bits in greenlet? How can I help or give more information? I've some information that it works with Python 3.4, but I can't prove it (yet).

**Comment by rafaelfolco** [comment]
Upstream version of OpenStack on ppc64 platform is blocked by this issue. 
A recent change on devstack dropped all rpm deps and started using pip versions. The result is a seg fault on "nova-manage db sync" during devstack deploy.

It seems to be an optimization issue. Building with -O1 works fine. The workaround is to force devstack installing greenlet-0.4.2 or 0.4.5 with -O1. Installing python-greenlet-0.4.2 from distro is also an alternative.

I assume the fix is in https://github.com/python-greenlet/greenlet/blob/master/platform/switch_ppc64_linux.h#L48 as described by https://github.com/python-greenlet/greenlet/issues/66.

Let me know what info I can provide or test I can run to help fixing this bug.

# export CFLAGS=-O1; ./setup.py install
running install
running build
running build_ext
building 'greenlet' extension
creating build
creating build/temp.linux-ppc64-2.7
gcc -pthread -fno-strict-aliasing -O3 -mtune=power7 -mcpu=power7 -g -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O3 -mtune=power7 -mcpu=power7 -g -D_GNU_SOURCE -fPIC -fwrapv -O1 -fPIC -I/usr/include/python2.7 -c greenlet.c -o build/temp.linux-ppc64-2.7/greenlet.o
creating build/lib.linux-ppc64-2.7
gcc -pthread -shared -Wl,-z,relro -O1 build/temp.linux-ppc64-2.7/greenlet.o -L/usr/lib64 -lpython2.7 -o build/lib.linux-ppc64-2.7/greenlet.so
running install_lib
copying build/lib.linux-ppc64-2.7/greenlet.so -> /usr/lib64/python2.7/site-packages
running install_headers
running install_egg_info
Removing /usr/lib64/python2.7/site-packages/greenlet-0.4.5-py2.7.egg-info
Writing /usr/lib64/python2.7/site-packages/greenlet-0.4.5-py2.7.egg-info


# ./run-tests.py 
running build_ext
Linking /tmp/greenlet/build/lib.linux-ppc64-2.7/greenlet.so to /tmp/greenlet/greenlet.so
python 2.7.8 (64 bit) using greenlet 0.4.5 from /tmp/greenlet/greenlet.so
test_dead_weakref (tests.test_weakref.WeakRefTests) ... ok
test_dealloc_weakref (tests.test_weakref.WeakRefTests) ... ok
test_inactive_weakref (tests.test_weakref.WeakRefTests) ... ok
test_version (tests.test_version.VersionTests) ... ok
test_exception_disables_tracing (tests.test_tracing.TracingTests) ... ok
test_greenlet_tracing (tests.test_tracing.TracingTests) ... ok
test_class (tests.test_throw.ThrowTests) ... ok
test_kill (tests.test_throw.ThrowTests) ... ok
test_throw_goes_to_original_parent (tests.test_throw.ThrowTests) ... ok
test_val (tests.test_throw.ThrowTests) ... ok
test_stack_saved (tests.test_stack_saved.Test) ... ok
test_arg_refs (tests.test_leaks.ArgRefcountTests) ... ok
test_kwarg_refs (tests.test_leaks.ArgRefcountTests) ... ok
test_threaded_adv_leak (tests.test_leaks.ArgRefcountTests) ... ok
test_threaded_leak (tests.test_leaks.ArgRefcountTests) ... ok
test_abstract_subclasses (tests.test_greenlet.GreenletTests) ... ok
test_dealloc (tests.test_greenlet.GreenletTests) ... ok
test_dealloc_other_thread (tests.test_greenlet.GreenletTests) ... ok
test_dealloc_switch_args_not_lost (tests.test_greenlet.GreenletTests) ... ok
test_deepcopy (tests.test_greenlet.GreenletTests) ... ok
test_exc_state (tests.test_greenlet.GreenletTests) ... ok
test_exception (tests.test_greenlet.GreenletTests) ... ok
test_frame (tests.test_greenlet.GreenletTests) ... ok
test_implicit_parent_with_threads (tests.test_greenlet.GreenletTests) ... ok
test_instance_dict (tests.test_greenlet.GreenletTests) ... ok
test_parent_equals_None (tests.test_greenlet.GreenletTests) ... ok
test_parent_restored_on_kill (tests.test_greenlet.GreenletTests) ... ok
test_parent_return_failure (tests.test_greenlet.GreenletTests) ... ok
test_recursive_startup (tests.test_greenlet.GreenletTests) ... ok
test_run_equals_None (tests.test_greenlet.GreenletTests) ... ok
test_send_exception (tests.test_greenlet.GreenletTests) ... ok
test_simple (tests.test_greenlet.GreenletTests) ... ok
test_switch_kwargs (tests.test_greenlet.GreenletTests) ... ok
test_switch_kwargs_to_parent (tests.test_greenlet.GreenletTests) ... ok
test_switch_to_another_thread (tests.test_greenlet.GreenletTests) ... ok
test_thread_bug (tests.test_greenlet.GreenletTests) ... ok
test_threaded_reparent (tests.test_greenlet.GreenletTests) ... ok
test_threaded_updatecurrent (tests.test_greenlet.GreenletTests) ... ok
test_threads (tests.test_greenlet.GreenletTests) ... ok
test_throw_doesnt_crash (tests.test_greenlet.GreenletTests) ... ok
test_throw_exception_not_lost (tests.test_greenlet.GreenletTests) ... ok
test_tuple_subclass (tests.test_greenlet.GreenletTests) ... ok
test_two_children (tests.test_greenlet.GreenletTests) ... ok
test_two_recursive_children (tests.test_greenlet.GreenletTests) ... ok
test_unexpected_reparenting (tests.test_greenlet.GreenletTests) ... ok
test_genlet_bad (tests.test_generator_nested.NestedGeneratorTests) ... ok
test_genlet_simple (tests.test_generator_nested.NestedGeneratorTests) ... ok
test_layered_genlets (tests.test_generator_nested.NestedGeneratorTests) ... ok
test_nested_genlets (tests.test_generator_nested.NestedGeneratorTests) ... ok
test_permutations (tests.test_generator_nested.NestedGeneratorTests) ... ok
test_generator (tests.test_generator.GeneratorTests) ... ok
test_circular_greenlet (tests.test_gc.GCTests) ... ok
test_dead_circular_ref (tests.test_gc.GCTests) ... ok
test_finalizer_crash (tests.test_gc.GCTests) ... ok
test_inactive_ref (tests.test_gc.GCTests) ... ok
test_getcurrent (tests.test_extension_interface.CAPITests) ... ok
test_new_greenlet (tests.test_extension_interface.CAPITests) ... ok
test_raise_greenlet_dead (tests.test_extension_interface.CAPITests) ... ok
test_raise_greenlet_error (tests.test_extension_interface.CAPITests) ... ok
test_setparent (tests.test_extension_interface.CAPITests) ... ok
test_switch (tests.test_extension_interface.CAPITests) ... ok
test_switch_kwargs (tests.test_extension_interface.CAPITests) ... ok
test_throw (tests.test_extension_interface.CAPITests) ... ok
test_exception_switch (tests.test_cpp.CPPTests) ... ok

----------------------------------------------------------------------
Ran 64 tests in 0.398s

OK

**Comment by alexschm** [comment]
Hi,

I submitted a pull request for this issue to fix s390x. While other archs are still broken, how about reintroducing the -fno-tree-dominator-opts CFLAG? The commit that removed the flag stated that this flag is obsolete and to be removed, but I could not find any evidence for this. It's still present in upstream gcc.

**Comment by snaury** [comment]
@alexschm that's odd, I rechecked and see now that it is indeed still supported even in gcc 5.1, and I can't remember where I saw that it was deprecated. Maybe I somehow confused gcc and clang together, where that flag was the most annoying: at first it was accepted, then it produced warnings, then it started to produce ugly errors. But to be honest I don't want to reintroduce that flag, it is a gcc-only band-aid, that won't work with anything else (even with gcc I'm not convinced it would always work, and not all platforms use gcc), it's always better to fix it properly (as you did for s390x).

**Comment by snaury** [comment]
@rafaelfolco I need a ppc64 instruction that can load a value 0 into a register (instead of `return 0`) to fix this, I'll see if I can find a cross-compiler, but it would be best if someone who knows the platform comes up with a fix.

**Comment by snaury** [comment]
@rafaelfolco ok, turns out ubuntu has a powerpc cross-compiler, so it was easy to find `li` does what I needed. Please try if HEAD now works with optimisations turned on.

**Comment by alexschm** [comment]
@snaury I tested head on a ppc64 system and it works fine again, thanks!

**Comment by rafaelfolco** [comment]
@snaury I also tested HEAD on ppc64 with default optimization, and confirm that the issue has disappeared. Thanks for the fix !

**Comment by snaury** [comment]
@gcsideal just release 0.4.6, please see if the situation improved.

**Comment by gcsideal** [comment]
@snaury Debian supports fourteen architectures. The compile round of 0.4.6 revealed that the PowerPC and s390x issues are solved. SPARC is still failing:
copying build/lib.linux-sparc-2.7/greenlet.so -> build/test-2.7
PYTHONPATH=build/test-2.7 python2.7 run-tests.py -n
python 2.7.9 (32 bit) using greenlet 0.4.6 from /[BUILDDIR]/build/test-2.7/greenlet.so
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
test_getcurrent (tests.test_extension_interface.CAPITests) ... ok
test_new_greenlet (tests.test_extension_interface.CAPITests) ... Illegal instruction
make[1]: *** [test-2.7-stamp] Error 132

MIPS(EL) built with 0.4.5 but now fails with:
PYTHONPATH=build/test-3.4 python3.4 run-tests.py -n
python 3.4.3 (32 bit) using greenlet 0.4.6 from /[BUILDDIR]/build/test-3.4/greenlet.cpython-34m.so
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
test_dead_weakref (tests.test_weakref.WeakRefTests) ... ok
test_dealloc_weakref (tests.test_weakref.WeakRefTests) ... Exception ignored in: <greenlet.greenlet object at 0x77637cb0>
ok
test_inactive_weakref (tests.test_weakref.WeakRefTests) ... ok
test_version (tests.test_version.VersionTests) ... ok
test_exception_disables_tracing (tests.test_tracing.TracingTests) ... Illegal instruction
make[1]: *** [test-3.4-stamp] Error 132

As our build infrastructure is under load, I still wait for the result of PPC64 build. All other architectures could build 0.4.6 .

**Comment by snaury** [comment]
@gcsideal there have been no changes for mips between 0.4.5 and 0.4.6, but I notice now I overlooked a fix for `return 0`, so the failure was probably always there and by chance it started failing now. :-/

As for sparc, @grzn sent me #78 just a week ago and verified that sparc works.

**Comment by snaury** [comment]
@gcsideal could you please see if this patch would fix mips? https://github.com/snaury/greenlet/commit/fa4a72e4e731d5619d07e9dfb0f2a773adc48ba2

**Comment by gcsideal** [comment]
@snaury The MIPSel fix is correct. The changes from @grzn is in 0.4.6 right? Still fails on our SPARC machines. :( PPC64 build is working. This means only the SPARC issue needs some more work, the others are solved.

**Comment by grzn** [comment]
@snaury I meant that with that fix, greenlet does not segfault in the specifc use-case I had with Solaris-11.

I'll run the greenlet tests today and let you know.

**Comment by grzn** [comment]
so, on my solaris-11-sparc, the following test crashes the same way with v0.4.5, v0.4.5, and my fix:
```
test_exception_switch (tests.test_cpp.CPPTests) ... terminate called after throwing an instance of 'exception_t'
terminate called recursively
```

**Comment by gcsideal** [comment]
@grzn For me it's different and constant with previous versions, including v0.4.6:
python 2.7.9 (32 bit) using greenlet 0.4.6 from /[BUILDDIR]/build/test-2.7/greenlet.so
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
test_arg_refs (tests.test_leaks.ArgRefcountTests) ... Illegal instruction
make[1]: *** [test-2.7-stamp] Error 132

All other architectures are fine now.

**Comment by snaury** [comment]
I tried looking up on how sparc architecture works, and looking at the current code I have no clue how it was ever working, or how it is even supposed to work. If I'm reading it correctly `ta 3` runs `flushw` in the kernel, which writes all saved register windows (except current) at their corresponding `%sp` places. There are multiple problems that I see:

* The biggest problem on the save side is that `%i7` that contains the return address is in the *current* window, so it is not spilled by `flushw`, and thus when `SLP_SAVE_STATE` tries to save the data it's probably some random garbage (fixing it would require doing `flushw` in `slp_save_state`, but it would only work if it allocates its own window, i.e. if compiler doesn't decide to omit `save` and `restore` for some reason, however since it's not a leaf function I'd guess such optimization is unlikely). However I can't find whether `ta 3` (which executes `flushw` in the kernel) allocates a new register window, so perhaps just because it's done with `ta 3` instead of `flushw` the registers actually happen to be spilled by chance.
* The biggest problem on the restore side is that even if we restore the stack as it was, it doesn't change `%i7`, so the return address is likely wrong and would return incorrectly.
* Another problem is that `ST_CLEAN_WINDOWS` seems to be about wiping registers of data from other threads, but as far as I can see in the Linux kernel source it's actually a bad trap and cannot be used. Besides, I don't see how someone would need to do that anyway, since context switching shouldn't change anything about windows in the current task.
* I'm thinking that to properly restore the state of `slp_switch` itself (and thus of `%i7` among other things) it should do a `ta 3` at the start of `slp_restore_state`. This way stack will be spilled into some random location, but we don't care about that, since all we need is registers restored after we overwrite the stack.

Given all that I have a preliminary fix in https://github.com/snaury/greenlet/tree/fix-sparc (@grzn, @gcsideal, please test https://github.com/snaury/greenlet/commit/081fd2e747af8fac3f5fdff231c35b9d70a9a479 if possible, I would clean it up later by moving sparc-specific bits out of greenlet.c, but I need to know if the idea works)

**Comment by grzn** [comment]
still not working:
{noformat}
root@host-vsparc01 (SunOS 5.11) ➜  greenlet-fix-sparc  python run-tests.py                                  15-05-10 09:02
running build_ext
Linking /root/greenlet-fix-sparc/build/lib.solaris-2.11-sun4v.64bit-2.7/greenlet.so to /root/greenlet-fix-sparc/greenlet.so
python 2.7.8 (64 bit) using greenlet 0.4.6 from /root/greenlet-fix-sparc/greenlet.so
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
test_dead_weakref (tests.test_weakref.WeakRefTests) ... ok
test_dealloc_weakref (tests.test_weakref.WeakRefTests) ... ok
test_inactive_weakref (tests.test_weakref.WeakRefTests) ... ok
test_circular_greenlet (tests.test_gc.GCTests) ... ok
test_dead_circular_ref (tests.test_gc.GCTests) ... ok
test_finalizer_crash (tests.test_gc.GCTests) ... ok
test_inactive_ref (tests.test_gc.GCTests) ... ok
test_genlet_bad (tests.test_generator_nested.NestedGeneratorTests) ... ok
test_genlet_simple (tests.test_generator_nested.NestedGeneratorTests) ... ok
test_layered_genlets (tests.test_generator_nested.NestedGeneratorTests) ... ok
test_nested_genlets (tests.test_generator_nested.NestedGeneratorTests) ... ok
test_permutations (tests.test_generator_nested.NestedGeneratorTests) ... ok
test_abstract_subclasses (tests.test_greenlet.GreenletTests) ... ok
test_dealloc (tests.test_greenlet.GreenletTests) ... ok
test_dealloc_other_thread (tests.test_greenlet.GreenletTests) ... ok
test_dealloc_switch_args_not_lost (tests.test_greenlet.GreenletTests) ... ok
test_deepcopy (tests.test_greenlet.GreenletTests) ... ok
test_exc_state (tests.test_greenlet.GreenletTests) ... ok
test_exception (tests.test_greenlet.GreenletTests) ... ok
test_frame (tests.test_greenlet.GreenletTests) ... ok
test_implicit_parent_with_threads (tests.test_greenlet.GreenletTests) ... ok
test_instance_dict (tests.test_greenlet.GreenletTests) ... ok
test_parent_equals_None (tests.test_greenlet.GreenletTests) ... ok
test_parent_restored_on_kill (tests.test_greenlet.GreenletTests) ... ok
test_parent_return_failure (tests.test_greenlet.GreenletTests) ... ok
test_recursive_startup (tests.test_greenlet.GreenletTests) ... ok
test_run_equals_None (tests.test_greenlet.GreenletTests) ... ok
test_send_exception (tests.test_greenlet.GreenletTests) ... ok
test_simple (tests.test_greenlet.GreenletTests) ... ok
test_switch_kwargs (tests.test_greenlet.GreenletTests) ... ok
test_switch_kwargs_to_parent (tests.test_greenlet.GreenletTests) ... ok
test_switch_to_another_thread (tests.test_greenlet.GreenletTests) ... ok
test_thread_bug (tests.test_greenlet.GreenletTests) ... ok
test_threaded_reparent (tests.test_greenlet.GreenletTests) ... ok
test_threaded_updatecurrent (tests.test_greenlet.GreenletTests) ... ok
test_threads (tests.test_greenlet.GreenletTests) ... ok
test_throw_doesnt_crash (tests.test_greenlet.GreenletTests) ... ok
test_throw_exception_not_lost (tests.test_greenlet.GreenletTests) ... ok
test_tuple_subclass (tests.test_greenlet.GreenletTests) ... ok
test_two_children (tests.test_greenlet.GreenletTests) ... ok
test_two_recursive_children (tests.test_greenlet.GreenletTests) ... ok
test_unexpected_reparenting (tests.test_greenlet.GreenletTests) ... ok
test_arg_refs (tests.test_leaks.ArgRefcountTests) ... ok
test_kwarg_refs (tests.test_leaks.ArgRefcountTests) ... ok
test_threaded_adv_leak (tests.test_leaks.ArgRefcountTests) ... ok
test_threaded_leak (tests.test_leaks.ArgRefcountTests) ... ok
test_class (tests.test_throw.ThrowTests) ... ok
test_kill (tests.test_throw.ThrowTests) ... ok
test_throw_goes_to_original_parent (tests.test_throw.ThrowTests) ... ok
test_val (tests.test_throw.ThrowTests) ... ok
test_getcurrent (tests.test_extension_interface.CAPITests) ... ok
test_new_greenlet (tests.test_extension_interface.CAPITests) ... ok
test_raise_greenlet_dead (tests.test_extension_interface.CAPITests) ... ok
test_raise_greenlet_error (tests.test_extension_interface.CAPITests) ... ok
test_setparent (tests.test_extension_interface.CAPITests) ... ok
test_switch (tests.test_extension_interface.CAPITests) ... ok
test_switch_kwargs (tests.test_extension_interface.CAPITests) ... ok
test_throw (tests.test_extension_interface.CAPITests) ... ok
test_exception_disables_tracing (tests.test_tracing.TracingTests) ... ok
test_greenlet_tracing (tests.test_tracing.TracingTests) ... ok
test_generator (tests.test_generator.GeneratorTests) ... ok
test_exception_switch (tests.test_cpp.CPPTests) ... terminate called after throwing an instance of 'exception_t'
terminate called recursively
{noformat}

**Comment by snaury** [comment]
@grzn C++ tests only work when exceptions don't use global variables (e.g. gcc with dwarf exceptions), if your compiler uses sjlj-style exceptions you should set `GREENLET_TEST_CPP=no` in your environment, since it cannot be supported.

**Comment by grzn** [comment]
Okay with that is works:
```
root@host-vsparc06 (SunOS 5.11) ➜  greenlet-fix-sparc  GREENLET_TEST_CPP=no python run-tests.py                                                               15-05-10 11:23
running build_ext
Linking /root/greenlet-fix-sparc/build/lib.solaris-2.11-sun4v.64bit-2.7/greenlet.so to /root/greenlet-fix-sparc/greenlet.so
python 2.7.8 (64 bit) using greenlet 0.4.6 from /root/greenlet-fix-sparc/greenlet.so
test_dead_weakref (tests.test_weakref.WeakRefTests) ... ok
test_dealloc_weakref (tests.test_weakref.WeakRefTests) ... ok
test_inactive_weakref (tests.test_weakref.WeakRefTests) ... ok
test_class (tests.test_throw.ThrowTests) ... ok
test_kill (tests.test_throw.ThrowTests) ... ok
test_throw_goes_to_original_parent (tests.test_throw.ThrowTests) ... ok
test_val (tests.test_throw.ThrowTests) ... ok
test_arg_refs (tests.test_leaks.ArgRefcountTests) ... ok
test_kwarg_refs (tests.test_leaks.ArgRefcountTests) ... ok
test_threaded_adv_leak (tests.test_leaks.ArgRefcountTests) ... ok
test_threaded_leak (tests.test_leaks.ArgRefcountTests) ... ok
test_exception_disables_tracing (tests.test_tracing.TracingTests) ... ok
test_greenlet_tracing (tests.test_tracing.TracingTests) ... ok
test_generator (tests.test_generator.GeneratorTests) ... ok
test_stack_saved (tests.test_stack_saved.Test) ... ok
test_genlet_bad (tests.test_generator_nested.NestedGeneratorTests) ... ok
test_genlet_simple (tests.test_generator_nested.NestedGeneratorTests) ... ok
test_layered_genlets (tests.test_generator_nested.NestedGeneratorTests) ... ok
test_nested_genlets (tests.test_generator_nested.NestedGeneratorTests) ... ok
test_permutations (tests.test_generator_nested.NestedGeneratorTests) ... ok
test_version (tests.test_version.VersionTests) ... ok
test_getcurrent (tests.test_extension_interface.CAPITests) ... ok
test_new_greenlet (tests.test_extension_interface.CAPITests) ... ok
test_raise_greenlet_dead (tests.test_extension_interface.CAPITests) ... ok
test_raise_greenlet_error (tests.test_extension_interface.CAPITests) ... ok
test_setparent (tests.test_extension_interface.CAPITests) ... ok
test_switch (tests.test_extension_interface.CAPITests) ... ok
test_switch_kwargs (tests.test_extension_interface.CAPITests) ... ok
test_throw (tests.test_extension_interface.CAPITests) ... ok
test_abstract_subclasses (tests.test_greenlet.GreenletTests) ... ok
test_dealloc (tests.test_greenlet.GreenletTests) ... ok
test_dealloc_other_thread (tests.test_greenlet.GreenletTests) ... ok
test_dealloc_switch_args_not_lost (tests.test_greenlet.GreenletTests) ... ok
test_deepcopy (tests.test_greenlet.GreenletTests) ... ok
test_exc_state (tests.test_greenlet.GreenletTests) ... ok
test_exception (tests.test_greenlet.GreenletTests) ... ok
test_frame (tests.test_greenlet.GreenletTests) ... ok
test_implicit_parent_with_threads (tests.test_greenlet.GreenletTests) ... ok
test_instance_dict (tests.test_greenlet.GreenletTests) ... ok
test_parent_equals_None (tests.test_greenlet.GreenletTests) ... ok
test_parent_restored_on_kill (tests.test_greenlet.GreenletTests) ... ok
test_parent_return_failure (tests.test_greenlet.GreenletTests) ... ok
test_recursive_startup (tests.test_greenlet.GreenletTests) ... ok
test_run_equals_None (tests.test_greenlet.GreenletTests) ... ok
test_send_exception (tests.test_greenlet.GreenletTests) ... ok
test_simple (tests.test_greenlet.GreenletTests) ... ok
test_switch_kwargs (tests.test_greenlet.GreenletTests) ... ok
test_switch_kwargs_to_parent (tests.test_greenlet.GreenletTests) ... ok
test_switch_to_another_thread (tests.test_greenlet.GreenletTests) ... ok
test_thread_bug (tests.test_greenlet.GreenletTests) ... ok
test_threaded_reparent (tests.test_greenlet.GreenletTests) ... ok
test_threaded_updatecurrent (tests.test_greenlet.GreenletTests) ... ok
test_threads (tests.test_greenlet.GreenletTests) ... ok
test_throw_doesnt_crash (tests.test_greenlet.GreenletTests) ... ok
test_throw_exception_not_lost (tests.test_greenlet.GreenletTests) ... ok
test_tuple_subclass (tests.test_greenlet.GreenletTests) ... ok
test_two_children (tests.test_greenlet.GreenletTests) ... ok
test_two_recursive_children (tests.test_greenlet.GreenletTests) ... ok
test_unexpected_reparenting (tests.test_greenlet.GreenletTests) ... ok
test_circular_greenlet (tests.test_gc.GCTests) ... ok
test_dead_circular_ref (tests.test_gc.GCTests) ... ok
test_finalizer_crash (tests.test_gc.GCTests) ... ok
test_inactive_ref (tests.test_gc.GCTests) ... ok

----------------------------------------------------------------------
Ran 63 tests in 0.762s

OK
```

but 0.4.6 also works with this environment variable...

**Comment by snaury** [comment]
@grzn what if you remove `os.environ["CFLAGS"] = ...` at the top of `setup.py`, would it still work in both cases? I suspect `-Os` is doing something that is hiding the problem, and I hope new code doesn't need it.

**Comment by grzn** [comment]
greenlet-0.4.6 passes with `-O3` and `GREENLET_TEST_CPP=no`:

```
gcc -fno-strict-aliasing -I/root/python/include -m64 -I/root/python/include/gnutls -I/root/python/include/graphviz -I/root/python/include/libexslt -I/root/python/include/libxml2 -I/root/python/include/libxslt -I/root/python/include/ncurses -I/root/python/include/openssl -I/root/python/include/readline -I/root/python/include/sasl -I/root/python/lib64/libffi-3.2.1/include -DNDEBUG -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -m64 -fPIC -I/root/python/include/python2.7 -c greenlet.c -o build/temp.solaris-2.11-sun4v.64bit-2.7/greenlet.o
```

and fails without the `GREENLET_TEST_CPP=no`

**Comment by snaury** [comment]
@grzn ok, thanks, I tried looking into illumos and found one implementation of `ST_CLEAN_WINDOWS` that does something like `save; flushw; restore`, which would (almost) explain how it worked on SunOS before. I hope new patch fixes Debian as well.

**Comment by grzn** [comment]
Alright; let me know when to run your patch through the scenario i have that caused 0.4.5 to crash with segmentation fault.



—

**Comment by snaury** [comment]
@gcsideal I haven't heard from you, but I had to release 0.4.7 for unrelated reasons (python 2.5 compatibility), so I included new sparc trick with it as well. Hope if finally works.

**Comment by gcsideal** [comment]
@snaury I couldn't test it (I can't reach a Sparc machine directly), so I didn't write. Now 0.4.7 is out for testing, will write about how it goes.

**Comment by gcsideal** [comment]
@snaury Now greenlet built on Sparc and on our other platforms as well, except kFreeBSD ones. The latter just need more time and as it was OK in the past I think those will be fine.

**Comment by rafaelfolco** [comment]
@snaury, greenlet is producing seg fault on ppc64le arch, which has the same registers as ppc64, but it is powerpc64le arch with different ABI. It apparently selects the right include file:platform/switch_ppc64_linux.h.
When I add a printf("xx") with 2+ chars it works fine. The seg fault vanishes.
Could you please give any sugegstions on how to fix this ? Thanks.

Linking /root/greenlet/build/lib.linux-ppc64le-2.7/greenlet.so to /root/greenlet/greenlet.so
python 2.7.8 (64 bit) using greenlet 0.4.7 from /root/greenlet/greenlet.so
test_dead_weakref (tests.test_weakref.WeakRefTests) ... Segmentation fault (core dumped)

**Comment by snaury** [comment]
@rafaelfolco see #89 for support, I'm waiting for an `#ifdef` in that PR before merging.

**Comment by awilfox** [comment]
I am not sure if this is a regression, but on greenlet 0.4.9 + gcc-4.8.4 + Linux on ppc32 (big endian, PowerPC G4), I am hitting the same issue as @rafaelfolco pointed out in March, and the -O1 addition to CFLAGS has fixed it for me (all tests pass and the server runs great).

I'm afraid the code is all a little too "magick" for me to understand properly to suggest a fix, but I can provide core dumps and generated assembly if necessary.

**Comment by snaury** [comment]
@awilfox yes, generated assembly would be very useful, could you please post a gist of the assembly that causes crashes and the assembly that doesn't?

**Comment by snaury** [comment]
@awilfox I created #94 for the issue, we should continue discussion there.
