### ISSUE TITLE
greenlet cause brew warning!

### ISSUE THREAD

**Issue by edonyM** [python-greenlet/greenlet#75]
I installed greenlet on my Mac with `pip install greenlet`. But when I use `brew doctor` to check my home-brew , it comes with warning.
```py
Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/python2.7/greenlet/greenlet.h
    /usr/local/include/python3.4m/greenlet/greenlet.h
```
My OS is OSX10.10.2. Is there any way to fix it?

**Comment by snaury** [comment]
The warning seems to be correct, pip install is putting that header there since it's part of the distribution. There are two solutions I could think of:

1) you could make a bug report on homebrew, so they add greenlet.h to a whitelist
2) you could create a formula for greenlet and install it via brew, not via pip

In any case, this is not a bug in greenlet, the header file is installed correctly by pip.

**Comment by edonyM** [comment]
Sincerely thank you, and I will make a bug report on homebrew. Personally, I prefer the second idea to solve this.
