### ISSUE TITLE
Add 'runcount' attribute

### ISSUE THREAD

**Issue by MichaelAz** [python-greenlet/greenlet#88]
Stackless has a [`runcount` attribute](http://stackless.readthedocs.org/en/latest/library/stackless/stackless.html#stackless.runcount) which returns the number of runable tasklets.
It'd be useful for greenlet to expose a similar attribute for the number of runnable greenlets.

(This would resolve gevent/gevent#465 whcih would in turn resolve rgalanakis/goless#27)

**Comment by snaury** [comment]
There's no concept of "runable tasklets" in greenlet. Each thread may have _one_ current and running greenlet, other are not running. There is no information that may suggest to greenlet which other greenlets may or may not run in the future, and greenlet doesn't even track those objects, it's the responsibility of frameworks that integrate them to the event loop.

Since you are talking about stackless and tasklets, you may try to implement stackless on top of greenlet, and since that would imply you would have some runable queue, you could then simply use its length as a `runcount` attribute.

**Comment by snaury** [comment]
Also, I would like to add that `gevent` already has a deadlock detector, it even helped me to detect deadlocks in my code several times, so I'm not sure what `goless` does to stop it from working properly.
